ExpConfig:
  dataset_dir: preprocessed/sekai-game-walking-352_192_30fps
  shift: 3
  bucket_config_name: ASPECT_RATIO_256  

  max_chunks: 20
  num: 24

  use_fixed_noise: true
  noise_cache_dir: configs/noise/352_192/noise0 
  checkpoint_path: weights/train-8-sft/steps1600.ckpt

OnlineTrainConfig:
  open: false
#finished at 2026-08-05 16:34:15 UTC+8, gpu num:8, run_name:infer-8-sft-sekai
