ExpConfig:
  dataset_dir: dataset/wbench
  shift: 3
  bucket_config_name: ASPECT_RATIO_256

  max_chunks: 20
  num: 8

  use_fixed_noise: true
  noise_cache_dir: configs/noise/352_192/noise0 
  checkpoint_path: weights/train-9-sft/steps200.ckpt

OnlineTrainConfig:
  open: false
#finished at 2026-08-06 22:26:36 UTC+8, gpu num:4, run_name:infer-9-sft-steps200-wbench
