ExpConfig:
  dataset_dir: preprocessed/sekai-game-walking-352_192_30fps
  shift: 3
  filter_weather: sunny
  num: 4

  checkpoint_path: "weights/train-5.7-add/steps450.ckpt"
  
  max_chunks: 15


OnlineTrainConfig:
  open: false
#finished at 2026-08-01 16:29:40 UTC+8, gpu num:4, run_name:infer-5.7-steps450
