train:
  data_dir: preprocessed/sekai-game-walking-647px-wrong-move
  shift: 5
  max_chunks_per_video: 10
  filter_location: "East Maddon Park, London, United Kingdom"
  filter_weather: sunny

  log_chunk: true

  cond_chunk_num: 16

  epochs: 1 
  # batch_size=gpu_num*1*max_chunks
  # steps_per_epoch=cases/gpu_num
  val_every_n_steps: 10

ttt:
  open: false
