ExpConfig:
  dataset_dir: dataset/wbench
  shift: 5
  bucket_config_name: ASPECT_RATIO_627_F64 

  max_chunks: 1
  num: 1

  use_fixed_noise: true
  noise_cache_dir: configs/noise/896_448/noise0 
  checkpoint_path: checkpoints/infinite_world_model.ckpt

OnlineTrainConfig:
  open: false
#finished at 2026-08-17 15:13:10 UTC+8, gpu num:1, run_name:infer-test-h20
